services:
  backend:
    image: hr-pulse-backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=sql-server-hr-pulse-2026.database.windows.net
      - DB_NAME=db-moubarak
      - DB_USER=${DB_USER_env}
      - DB_PASSWORD=${DB_PASSWORD_env}
      - DB_DRIVER={ODBC Driver 18 for SQL Server}
    restart: always

  frontend:
    image: hr-pulse-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always